### ISSUE TITLE
インデックスページからチュートリアルへのリンクgithub pages経由でリンク切れしてる

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/tutorials#14]
https://chirimen.org/tutorials/
でリンク切れです。
理由は、github pagesはcase sentiiveかつ拡張子も必要のため

github pages止めるか、pagesでもリンク切れないようにcaseを合わせるかどちらか

**Comment by satakagi** [comment]
多分今はあまり意味のない
/RaspberryPi/JA/
こっちのページをリンク切れないように直してみました。
このページがtutorials.chirimen.orgからでも問題ないなら、
/
のほうのページの中身も同じように修正するか　github pagesを廃止するかどちらかですね。

**Comment by satakagi** [comment]
https://tutorial.chirimen.org/raspberrypi/ja/
で試しにアクセスしてみたら、
.md拡張子がついているとうまくないですね。
どうしますか？ @dynamis

**Comment by dynamis** [comment]
こちら返事できていなくてごめんなさい (口頭では少し話したと思いますが)。
github pages ではなく netlify で使う方を本番サイトとする想定をしています

基本的には tutorial.chirimen.org 配下、.html とか .md とかの拡張子無しのシンプルかつ小文字に統一の URL に統一するのが見た目も綺麗だし大文字小文字間違えても勝手にリダイレクトされるし、ユーザ目線で良いと考えています。

github pages のほうは誤解がないように無効化しておきます。

リンクするときはそういう URL になると言うことだけ考えて、github pages の時と同じように markdown ファイルを書き換えていってもらえれば大丈夫な、Jekyll テンプレートをカスタマイズしたからといって編集者が分からなくなったり難しくなったりする要素は極力排除したつもりです。
