### ISSUE TITLE
変数vの宣言漏れ

### ISSUE THREAD

**Issue by sa-maeda** [chirimen-oh/tutorials#20]
https://tutorial.chirimen.org/raspi3/ja/section0#javascript

上記の箇所について `v` の宣言が抜けているように見受けられます。
追記いただけますようお願いします。

**Comment by dynamis** [comment]
ご指摘ありがとうございます！

**Comment by sa-maeda** [comment]
https://github.com/chirimen-oh/chirimen-raspi3/blob/master/gc/gpio/LEDblink/main.js
上記と同等になる想定で考えておりました。

`var v ^= 1` だと SyntaxError となってしまわないでしょうか?

**Comment by dynamis** [comment]
ああぁ、かなりボケをかましました。

こちらのコミットで直しました: https://github.com/chirimen-oh/tutorials/commit/04192c661a614c76779b666ffb81e8ea119512f5
