### ISSUE TITLE
idの不一致

### ISSUE THREAD

**Issue by sa-maeda** [chirimen-oh/tutorials#22]
https://tutorial.chirimen.org/raspi3/ja/section2#jsfiddle%E3%81%A7html%E3%82%92%E6%9B%B8%E3%81%8F

上記で、htmlで指定しているidが `value`なのに、javascript部分のquerySelectorで指定しているidが `#ADT7410value` となっています。
どちらかに統一をお願いいたします。

**Comment by dynamis** [comment]
https://github.com/chirimen-oh/tutorials/blob/master/raspi3/examples/section2/s2_2.html
でも ADT7410value ですのでそちらに合わせました。

修正を含むコミットはこちら: https://github.com/chirimen-oh/tutorials/commit/8326374f0e9bf016f98bc1314c9b975dc40208fd
