### ISSUE TITLE
講師向けページの作成

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/tutorials#28]
チュートリアルを使って講義を行う講師が注意すべきポイントなどを書いたドキュメントページを用意する。

**Comment by dynamis** [comment]
- [ ] スターターキットの部材に込められた意味
  - わざと混在させているものについてその意図とどう指導すべきかという話
- [ ] タクトスイッチに関する注意
- [ ] DC ファンの極性に関する注意
- [ ] その他のセンサーは色々用意して試せるように誘導すべき点
- [ ] ショートすると燃えたり火傷するので配線に注意が必要だしボードやセンサー類を触るときには注意が必要だという話
- [ ] 一般 Web 開発との連携について

and more...

**Comment by dynamis** [comment]
参考情報メモ
:
- https://peraichi.com/landing_pages/view/hhm2a
- https://gist.github.com/elie-j/8a27e7a65a40371e0cda5754ce0a063d

**Comment by saxAllan** [comment]
typo修正しました。

**Comment by dynamis** [comment]
一通り書いたのでクローズ
