### ISSUE TITLE
リモートデスクトップの説明ページ

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/tutorials#29]
PC を持ち込んでリモートデスクトップで開発する場合のためのヘルプページを書く

ref: https://qiita.com/t114/items/bfac508504b9a6b7570d

**Comment by saxAllan** [comment]
tipsに追記しました。
なお、文章内リンク先がqiitaのままになっています。

**Comment by dynamis** [comment]
中身をそのままコピペしてきちゃダメです！
これでは完全に著作権違反になってしまいます。参考にしつつ自分の文章として書く必要があります。
該当する Qiita 以外にも、自分で試して見て気になる点や他に便利な手順など色々調べた上で、説明を書くようにしてください。最終的にコマンドが同じになっても良いですが、文章まるごとコピペは許されません。

**Comment by saxAllan** [comment]
大変申し訳ありません。取り急ぎコピペ部分の削除を行い、数日中に自身で内容の制作をします。

**Comment by saxAllan** [comment]
内容を独自に製作し、https://github.com/chirimen-oh/tutorials/blob/master/raspi3/ja/tips.md に追記しました。
ひとまず説明にはなってるのでcloseします。
