### ISSUE TITLE
edit this page on github リンクを付ける

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/tutorials#31]
「現在のページを GitHub で編集する」リンクをテンプレートの末尾に追加したいというメモです:

多分ココ弄るだけで簡単にできるが変数名とか調べる必要があるのでまた今度:
https://github.com/chirimen-oh/tutorials/blob/master/_layouts/default.html

**Comment by sizuhiko** [comment]
GitHubの該当ファイルへのリンクを付けるので良ければ対応します

**Comment by dynamis** [comment]
見逃してました。該当 md ファイルへのリンクだけで十分です。是非是非。

**Comment by dynamis** [comment]
Thanks a lot!
