### ISSUE TITLE
jsbin で for/while ループが動かない問題について

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/tutorials#33]
for / while の無限ループが一度しか実行されないという謎挙動の報告が時々あった問題、ローカル HTML では問題ないけど何でだろうと思ったら、jsbin の親切によって自動的に無限ループを検知して無効化する機能が止めていたようです。は // noprotect ってコメントを入れると無効化できる機能のようです

https://jsbin.com/blog/protection/

そもそも無限ループって良くないコードの書き方だけどわかりやすいからと言うだけで使われているのだと思いますが、jsbin 使わせる上でハマる人がでてかわいそうなのでもう少し考えるか何かしないとかも

**Comment by saxAllan** [comment]
JSBin の JS に一通り `// noprotect` を追記して対応しました。
