### ISSUE TITLE
旧チュートリアル (Qiita 版) へのリンクは別ページに

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/tutorials#37]
チュートリアル目次 https://tutorial.chirimen.org/raspi3/ja/ を開くとつい一番下までスクロールして旧チュートリアル (Qiita 版)のページを開いてしまうことがあるが、目次がなんか長いページになりすぎてきた気がするし、基本的には最新版を見てもらった方が良いので、オリジナルへのリンクは古いドキュメントの紹介ページなり謝辞のページなりを作成してそちらに移した方が良かったかも。

**Comment by saxAllan** [comment]
ひとまず、旧チュートリアルのリンクを別ページに移動し、目次ページにはそのページへのリンクのみ残しました。

**Comment by dynamis** [comment]
https://github.com/chirimen-oh/tutorials/commit/df3fdde2b0ce5f5a0e01e602c323bf9982c10886 ですね。issue 解決時はコミットログに issue 番号 (#xx) をつけてコミットしてくれるか issue に書き込んで報告してくれると嬉しいです。

sectionN.md はチュートリアル本編用なので過去のページは別の名前にしてください。
deprecated.md とか original.md とか何でも良いので。あるいは謝辞ページなどとして纏めてその中の一部としてオリジナルへのリンクをする thanks.md とかだとなお良いかもです。

**Comment by dynamis** [comment]
完了しているのでクローズ
