### ISSUE TITLE
サンプルソースをasync await ただしallow無しで統一する

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/tutorials#4]
対象とするファイルは
gc/i2c/*.js
と
gc/gpio/*.js
でしょうか。

**Comment by satakagi** [comment]
このサンプルコード(for I2C Devices)に関係する、チュートリアル(Section3)を方針に沿って書き換えました。

**Comment by satakagi** [comment]
examplesディレクトリにサンプルソースを持ってきました。
section3分は、まだテストできていません。

**Comment by dynamis** [comment]
多分完了済みなのでクローズ
