### ISSUE TITLE
スターターキット変更に合わせて基礎編を更新

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/tutorials#41]
スターターキットの中身を変更 #40 するのが確定したらそれに合わせてチュートリアルを書き換える。

- [x] 更新開始前にタグを打っておく (ブランチを残して branch deploy させるのもよい)
  - webiot-2018 ブランチ https://github.com/chirimen-oh/tutorials/tree/webiot-2018
- [x] 旧チュートリアル向けのページはバックアップとして何処かでみられるようにする
  - ブランチデプロイ https://webiot-2018--tutorial-chirimen-org.netlify.com/
- [x] 旧チュートリアル向けの案内を追加
  - https://github.com/chirimen-oh/tutorials/commit/25374dcc43a16f642b0db3211fa13698d32cad9f
- [x] 新しい部材を前提としたものに書き換えを進める
  - [x] https://tutorial.chirimen.org/raspi3/ja/section1
    - [x] 回路図の更新
      - https://github.com/chirimen-oh/tutorials/blob/master/raspi3/ja/imgs/section1/DC3.png は https://github.com/chirimen-oh/tutorials/blob/master/raspi3/ja/imgs/section1/DC3.fzz の png 出力      
      - fzz ファイルの編集はこちらでする http://fritzing.org/home/
      - png と一緒に必ず fzz もペアで更新すること
      - 出力画像はオリジナル解像度のままで。解像度変更は別途 #39 でおこなう
    - [x] 説明文
    - タクトスイッチ 2pin にメインの流れを統一
      - 4pin 向け情報は残す、回路図も両方用意して 4pin も参照可能に
    - オスオスジャンパーワイヤー
    - ちびギアモーターセット
      - https://tiisai.dip.jp/?p=2676
      - https://tiisaishop.dip.jp/product/sg/
  - [x] https://tutorial.chirimen.org/raspi3/ja/section3
  - [x] 距離センサー本文を GP2Y0E03 から I2C-VL53L0X に
    - [x] 「他の I2C モジュールも使ってみる」に GP2Y0E03 を追記
    - [x] jsbin を用意する
      - 編集完了後、save as template して new してから (一度少しでも編集して) Ctrl+S で保存
      - 他の Advenced Example も同様にしたい -> https://github.com/chirimen-oh/chirimen-raspi3/issues/60
    - [x] リダイレクト設定を追加 https://r.chirimen.org/i2c-vl53l0x
      - 追加先: https://github.com/chirimen-oh/r.chirimen.org/blob/master/_redirects
- [x] ADT7410 火傷対策 https://tutorial.chirimen.org/raspi3/ja/section2
  - [x] 温度センサーは変わらないが、火傷対策のため最初に指で持たせないよう工夫したい。
    - 実際に配線して裏表がはっきりと分かる画像を追加する
    - 写真は見るので、写真の中にも「裏表逆に刺すと壊れて火傷するよ！」って注意書きを入れる
    - 文章の説明も適当に上手く工夫してください

**Comment by dynamis** [comment]
変更前のものは webiot-2018 branch 切った:
https://github.com/chirimen-oh/tutorials/tree/webiot-2018

2018 年度版のスターターキットで取り組みたい人はブランチデプロイしたサイトを見れば良い https://webiot-2018--tutorial-chirimen-org.netlify.com/

**Comment by satakagi** [comment]
ブレッドボードの図：
https://github.com/chirimen-oh/tutorials/blob/master/raspi3/ja/imgs/section1/DC3motor.png
そのソースコード（ちびギアモータのパーツを新たに制作）
https://github.com/chirimen-oh/tutorials/blob/master/raspi3/ja/imgs/section1/DC3motor.fzz

Section1の該当部分はコメント行として上記ブレッドボード図を書き込んであります：
https://github.com/chirimen-oh/tutorials/blob/master/raspi3/ja/section1.md

**Comment by dynamis** [comment]
チェックリスト漏れ。section 4 でも DC ファンが出てきてるので置き換えが必要
- [ ] https://tutorial.chirimen.org/raspi3/ja/section4

**Comment by dynamis** [comment]
section5 の変更は結構大変そう。発展編だし特に推奨センサーじゃなく GP2Y0E03 無くても良いからそのままにするか、VL53L0X or GP2Y0E03 どちらかを使って下さいくらいとして説明文とコードだけ直すのでも良いかも。

**Comment by dynamis** [comment]
- [ ] デスクトップスクリーンショット古い
  - https://tutorial.chirimen.org/raspi3/imgs/section0/CHIRIMENforRaspberryPi3desktop.png

**Comment by dynamis** [comment]
section5 はスターターキットを使ったものではないし対象外としてクローズ
