### ISSUE TITLE
Hello Real Worldに、SDイメージの焼き方の紹介は要りませんか？

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/tutorials#45]

**Comment by dynamis** [comment]
確かに。sdcard の準備手順ページへのリンクは secrion0 とか debug の文中からしかなかったですね。完全にスターターキット保ってる人のことしか考えられてないサイトですね。

https://tutorial.chirimen.org/raspi3/ja/sdcard

への誘導をどこか最初に見に来るであろう場所いくつかに書き足しましょう。

**Comment by dynamis** [comment]
一通り誘導を調整し終わったのでクローズ。
