### ISSUE TITLE
DC ファン配線図を配線ミスしにくい (見やすい) ものにしたい

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/tutorials#5]
https://github.com/chirimen-oh/tutorials/blob/master/RaspberryPi/JA/imgs/section1/DC3.png

* 10k と 1k の抵抗がディスプレイの発色が良いものを使わないと見間違える学生が出てくることが多い
  * よく見ろと言ってもミスするので、抵抗だけ大きくズームして配色の判別がつくようにしたい
* 黒いジャンパーピンを内側の GND ピンではなく外側の GPIO 21 番ピンに繋ぐ学生がでてくる
  * 回路的にもコード的にも何を繋いでいるか考えれば明らかなんだけど、図として見にくいのは確か。黒いジャンパーピンは右からではなく左から回り込む図にした方が間違いにくい

**Comment by satakagi** [comment]
実態配線図のソースデータも共有した方が良いですね。

**Comment by tadfmac** [comment]
すごい切り貼りで作ってるんですよね。。。
Sketch.app のデータなので、Macでしか編集できないです。

**Comment by dynamis** [comment]
この手のもののための標準ツールがあって使っているわけじゃなかったのですね。
fritzing とかだと思っていたら Sketch.app のデータですか。

https://www.sketchapp.com/pricing/ だと有料アプリなのでちょっと辛いですね

ちなみにサイズの小さなファイルなら issue のコメント記入欄にドロップするだけでもアップロード (＆リンク) できたりします。

**Comment by tadfmac** [comment]
> https://www.sketchapp.com/pricing/ だと有料アプリなのでちょっと辛いですね

..... 本コミュニティでは、別repoにeagleのデータもHWデザインとして共有している時点で、特に有料アプリだと辛いという感覚はないですが.....

**Comment by satakagi** [comment]
ベースの絵はfritzingで作っていると思うのですが、できるだけfritzingで作るという方針は良いですよね？

**Comment by satakagi** [comment]
テスターを使った抵抗の測定方法、0章に外部サイトへのリンクを張りました。

**Comment by satakagi** [comment]
![dcfan](https://user-images.githubusercontent.com/6793745/44965631-8c036c80-af71-11e8-83b3-ba64e4f0a408.png)
このぐらいまではFritzingだけで編集できますが、これで十分ではないでしょうか？
