### ISSUE TITLE
partslist ページの内容拡充

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/tutorials#56]
悟さんがパーツリストを追加してくれたので、より見やすくしていきたい

https://tutorial.chirimen.org/raspi3/partslist

- [x] 製品情報・データシート・解説ページへのリンク
- [x] 購入先例へのリンク
- [x] できること、用途の簡単な説明を追加
- [x] よく使われるアナログセンサーを追加、一部アナログセンサーが GPIO センサ 配下にあるので移動
- [ ] 同じセンサーで違う見た目のパーツは写真の例を追加
- [x] 抵抗も初学者向けの大きい (抵抗値が見やすい) 購入先を紹介
- [ ] netlify の url ルールに合わせて修正 (小文字ファイル名.md へリンク)

参考: CHIRIMEN 対応機材リスト表
https://docs.google.com/spreadsheets/d/1sUfxTwuiZoupeFvbIj5sLJrwgZQy2uFMKibi8KbLAnA/edit#gid=0

**Comment by saxAllan** [comment]
ひとまず、「I2C センサー」の項に販売ページへのリンクを用意し、Examplesへのリンクを独立させておきました。販売ページ内に製品詳細が記載されている販売先を選んだので、1つ目と2つ目のチェックリストは併合してしまって良い気もします。

**Comment by saxAllan** [comment]
各種リンクの列を作り、製品に関する情報へのリンクをまとめました。

**Comment by kou029w** [comment]
[partslistページ](https://tutorial.chirimen.org/raspi/partslist.html)のデータがあまりにも膨大だったので[_data/partslist.csv](https://github.com/chirimen-oh/tutorials/blob/master/_data/partslist.csv)にCSVファイルとして外部化しました

**Comment by kou029w** [comment]
これらは別課題として起票後に本Issueはクローズしたいと思います

> - [ ] 同じセンサーで違う見た目のパーツは写真の例を追加
> - [ ] netlify の url ルールに合わせて修正 (小文字ファイル名.md へリンク)

**Comment by kou029w** [comment]
> - [ ] netlify の url ルールに合わせて修正 (小文字ファイル名.md へリンク)

よく分からないが少なくともREADME.md以外ファイル名に[A-Z]を含むファイルは存在しないように見えるのでクローズ。
