### ISSUE TITLE
polyfill.jsの標準的なURLを決めるべき

### ISSUE THREAD

**Issue by satakagi** [chirimen-oh/tutorials#6]
サンプルによって、
https://mz4u.net/libs/gc2/polyfill.js
だったり、ローカルのものにアクセスしていたりしますね。
混乱のもとになりそう

**Comment by tadfmac** [comment]
2018/03/08版より rawgit側に寄せていますが、Web x IoT メイカーズチャレンジ 2017 で使った環境から急にドキュメント含めて変えてしまうと（イベント後の継続学習等への）影響が懸念されたため、あえて Qiita側のリンクは変えずに残しておきました。

時期を見て現在のimageに合わせようと思っています。

**Comment by dynamis** [comment]
次の issue にて記載の通りファイル名等は決まったのでこちらはクローズしておきます。

https://github.com/chirimen-oh/chirimen-raspi3/issues/29
