### ISSUE TITLE
raspi3 to raspi

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/tutorials#63]
Raspberry Pi4 を正式サポートすることになった
https://github.com/chirimen-oh/chirimen-raspi3/issues/84

また、Jetson Nano のベータリリースに向けて進めることになった。故にあちこち CHIRIMEN for Raspberry Pi3 を単に CHIRIMEN としたり raspi3 を raspi としたりという変更をしていく。
https://github.com/chirimen-oh/chirimen-raspi3/issues/86

本チュートリアルでは以下の変更を想定

- [x] raspi3 と書かれている部分を raspi に、raspi4 を動作環境として追記
  - [x] hellorealworld.md
  - [x] hellorealworld.pdf
  - [x] section0
  - [x] section1
  - [x] section2
  - [x] section3
  - [x] section4
  - [x] section5
  - [x] section6
- [x] raspi3 ディレクトリを raspi にしてリダイレクト
  - https://github.com/chirimen-oh/tutorials/blob/master/_redirects
- jetson nano については簡単なイントロだけで済ませる (初心者向けは Raspi に任せて中上級者向けの位置づけ) - 別 issue に分離: https://github.com/chirimen-oh/tutorials/issues/67
- node から使うものも同様。 - 別 issue に分離 https://github.com/chirimen-oh/tutorials/issues/68

**Comment by saxAllan** [comment]
- [ ] sdcardも書き換えが必要

**Comment by saxAllan** [comment]
ここに上がっている分は修正完了し、一通り修正が住んだと思われるためクローズ
