### ISSUE TITLE
Qiita へのリンクをこのリポジトリ内の相互リンクに変更する

### ISSUE THREAD

**Issue by dynamis** [chirimen-oh/tutorials#7]
チュートリアル本文中のリンクが一部 qiita 行きになっているので修正する:

https://github.com/chirimen-oh/tutorials/search?q=qiita&unscoped_q=qiita

**Comment by satakagi** [comment]
わかる範囲ですべてリンクを修正しました。

**Comment by dynamis** [comment]
verified. closing...
