### ISSUE TITLE
about ページからのリンク切れ

### ISSUE THREAD

**Issue by elie-j** [chirimen-oh/tutorials#74]
https://tutorial.chirimen.org/about　から誘導のある

* CHIRIMEN for Raspberry Pi3 のチュートリアル
https://tutorial.chirimen.org/raspi/ja/

* CHIRIMEN with ty51822r3 のチュートリアル
https://tutorial.chirimen.org/ty51822r3/ja/

がそれぞれリンク切れになります。
/ja/ のせい？

**Comment by dynamis** [comment]
ご指摘ありがとうっ！

ja/ 外しました。他言語対応 URL ルールが確か途中で変わってリンク修正漏れかと思います。
